Invoice/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.homepage,name='invoice-homepage'),
    path('add_items/<str:id>/', views.add_items, name='add-items'),
    path('update_items/<str:id>/<int:pk>', views.item_update, name='update-items'),
    path('delete_items/<str:id>/<int:pk>', views.item_delete, name='delete-items'),
    path('history/<str:id>/', views.history, name='history'),
    path('generate-pdf/<str:id>/<str:type>', views.generate_pdf, name='generate-pdf'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Invoice_Generator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Invoice.urls')),
]

Invoice/models.py
import uuid
from django.db import models
from datetime import datetime
from zoneinfo import ZoneInfo

def get_current_time_utc530():
    tz = ZoneInfo("Asia/Kolkata")  # UTC+05:30 timezone
    return datetime.now(tz)

ADDRESS_CATEGORY = (
    ('Gujarat Refinery','Gujarat Refinery'),
)

RETURNABLE_CATEGORY = (
    ('Returnable','Returnable'),
    ('Non-Returnable','Non-Returnable'),
)

NAMES = (
    ('Kesaba Trilochan Panda','Kesaba Trilochan Panda'),
    ('Rakshit Singh','Rakshit Singh'),
)

# Create your models here.
class letter_information(models.Model):
    letter_id = models.UUIDField(default=uuid.uuid4, unique=True)
    address = models.CharField(max_length=30, choices=ADDRESS_CATEGORY)
    returnable = models.CharField(max_length=20, choices=RETURNABLE_CATEGORY)
    source = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    date = models.DateTimeField(default=get_current_time_utc530)
    name=models.CharField(max_length=50, choices=NAMES)

    def __str__(self):
        # return f'{self.returnable} pass from {self.address} to {self.destination}'
        return f'{self.letter_id}'
    
    
class list_of_items(models.Model):
    table_id = models.CharField(max_length=150)
    description = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural='list_of_items'
    

Invoice/forms.py
from django import forms
from .models import letter_information,list_of_items

class Letter_info_form(forms.ModelForm):
    class Meta:
        model=letter_information
        fields=['address','returnable','source','destination','name']

class Add_items_form(forms.ModelForm):
    class Meta:
        model=list_of_items
        fields=['description','quantity']



        

Invoice/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import Letter_info_form,Add_items_form

from .models import letter_information,list_of_items

# Create your views here.
def homepage(request):
    if(request.method=='POST'):
        form=Letter_info_form(request.POST)
        if form.is_valid():
            form.save()
            last=letter_information.objects.last()
            data_row = [str(getattr(last, field.name)) for field in letter_information._meta.fields]
            return redirect('add-items',id=data_row[1])

    else:
        form=Letter_info_form()

    context={
        'form':form
    }

    return render(request,'Invoice/letter_info.html',context)


def add_items(request,id):

    items=list_of_items.objects.all()
    information = letter_information.objects.get(letter_id=id)

    if(request.method=='POST'):
        form=Add_items_form(request.POST)
        form_info=Letter_info_form(request.POST,instance=information)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.table_id=id
            instance.save()
            return redirect('add-items',id=id)
        
        if form_info.is_valid():
            form_info.save()
            return redirect('add-items',id=id)
    else:
        form=Add_items_form()
        form_info=Letter_info_form(instance=information)

    context = {
        'form':form,
        'form_info':form_info,
        'items':items,
        'id':id,
    }

    return render(request,'Invoice/letter_items.html',context)

def item_update(request,id,pk):
    item=list_of_items.objects.get(id=pk)
    if(request.method=='POST'):
        form=Add_items_form(request.POST, instance=item)
        if(form.is_valid()):
            form.save()
            return redirect('add-items',id=id)
    else:
        form=Add_items_form(instance=item)

    context={
        'form':form,
        'id':id,
    }
    return render(request,'Invoice/item_update.html',context)

def item_delete(request,id,pk):
    item=list_of_items.objects.get(id=pk) 
    if(request.method=='POST'):
        item.delete()
        return redirect('add-items',id=id)

    context={
        'id':id
    }
    return render(request,'Invoice/item_delete.html',context)


def history(request,id):
    if id==' ':
        info=letter_information.objects.last()   
        data_row = [str(getattr(info, field.name)) for field in letter_information._meta.fields ]
        letter_id=data_row[1]
    else:
        letter_id=id

    information = letter_information.objects.get(letter_id=letter_id)

    info=letter_information.objects.all().order_by('-id')
    items=list_of_items.objects.all()

    if(request.method=='POST'):
        new_id=request.POST.get('id')
        return redirect('history',id=new_id)

    context = {
        'id': letter_id,
        'information':information,
        'info':info,
        'items':items,
    }

    return render(request,'Invoice/history.html',context)




from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from django.apps import apps

def generate_pdf(request, id, type):
    response = HttpResponse(content_type = 'application/pdf')
    response['Content-Disposition'] = f'{type}; filename=Letter.pdf'

    pdf=canvas.Canvas(response,pagesize=letter)
    pdf.setTitle('PDF Report')

    image_path = 'images/indianoil_image.png'  # Replace with the actual path to your image
    image = ImageReader(image_path)
    pdf.drawImage(image, x=0, y=600, width=620, height=200, mask='auto', preserveAspectRatio=True)

    info_model=letter_information.objects.get(letter_id=id)

    fontsize=12

    pdf.setFont("Helvetica-Bold", fontsize)
    
    address_start = 550
    pdf.drawString(30,address_start,'To,')
    pdf.drawString(30,address_start- fontsize - 3,'The Security In-charge')
    pdf.drawString(30,address_start- fontsize*2 - 6,f'{info_model.address}')

    pdf.drawString(470,address_start,f'Date: {info_model.date.strftime("%d/%m/%Y")}')
    
    subject_start_x=130
    subject_start_y=470
    subject_string = f'Sub: Request for {info_model.returnable} Gate Pass'
    pdf.drawString(subject_start_x,subject_start_y,subject_string)
    
    # Draw the underline
    text_width = pdf.stringWidth(subject_string, "Helvetica-Bold", fontsize)
    underline_y = subject_start_y - 2  # Position the underline slightly below the text
    pdf.line(subject_start_x, underline_y, subject_start_x + text_width, underline_y)

    pdf.setFont("Helvetica", fontsize)

    main_letter_1=f'This is to request you to allow the following from {info_model.source}'
    main_letter_2=f'to {info_model.destination}'
    pdf.drawString(40,400,main_letter_1)
    pdf.drawString(40,400-fontsize-3,main_letter_2)

    headers = [field.verbose_name.capitalize() for field in list_of_items._meta.fields]
    del headers[0]
    headers[0]='Sr.No.'
    data = [headers]

    counter=1
    queryset=list_of_items.objects.all()
    for obj in queryset:
        data_row = [str(getattr(obj, field.name)) for field in list_of_items._meta.fields ]
        if data_row[1]==id:
            del data_row[0]
            data_row[0] = str(counter)
            counter=counter+1
            data.append(data_row)

    col_widths = [50, 300, 80]
    table = Table(data,colWidths=col_widths)
    table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),  # Header row font
        ('FONTSIZE', (0, 0), (-1, 0), 12),  # Header row font size
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),  # Header row bottom padding
        ('GRID', (0, 0), (-1, -1), 1, colors.black),  # Add grid lines
    ]))

    canvas_width = 600
    canvas_height = 600

    # table.wrapOn(pdf, canvas_width, canvas_height)
    table_width, table_height = table.wrapOn(pdf, canvas_width, canvas_height)
    table_y = 350 - table_height
    table.drawOn(pdf, 80, table_y)

    pdf.setFont("Helvetica-Bold", fontsize)
    pdf.drawString(400,100,info_model.name.upper())
    text_width = pdf.stringWidth(info_model.name.upper(), "Helvetica-Bold", fontsize)
    pdf.drawCentredString(400+text_width/2,100-fontsize-3,'ISO')

    pdf.save()
    return response

templates/Invoice/history.html
{% extends 'partials/base.html' %}

{% block styling %}
    select{
        width:500px;
        height:50px;
    }
    #history_div{
        width:500px;
        margin:50px;
    }
{% endblock %}

{% block content %}
<div id="history_div">

    <form method="POST">
        {% csrf_token %}
        <select class="form-select" name="id" aria-label="Default select example">
            <option selected value="{{information.letter_id}}">{{information.date}}</option>
            {% for i in info %}
            {% if information.letter_id != i.letter_id %}
            <option value="{{i.letter_id}}">{{i.date}}</option>
            {% endif %}
            {% endfor %}
        </select>
        <input class="btn btn-success btn-block" type="submit" value="Search">
    </form>
</div>


<div class="row my-4">
    <div class="col-md-4" style="margin-left:20px;" >
        <div class="bg-info text-white p-3 mb-3 ">
            <h5>Letter information</h5>
            <hr>
                <!-- <form method="POST">
                    {% csrf_token %}
                    {{ form_info }}
                    <input class="btn btn-success btn-block" type="submit" value="Save">
                </form> -->
            
            <p>
                Address : {{information.address}}
            </p>
            <p>
                {{information.returnable}}
            </p>
            <p>
                Source : {{information.source}}
            </p>
            <p>
                Destination : {{information.destination}}
            </p>
            <p>
                From : {{information.name}}
            </p>
            
        </div>
        <a href="{% url 'generate-pdf' id 'attachment' %}" class=" active alert alert-info" > Generate PDF </a>
        <a href="{% url 'generate-pdf' id 'inline' %}" style="margin-left:20px;" target="_blank" class=" active alert alert-info" > Preview PDF </a>
    </div>
    <div class="col-md-7" style="margin-right:10px;">
        <table class="table bg-white">
            <thead class="bg-info text-white">
                <tr>
                    <th scope="col">Description</th>
                    <th scope="col">Quantity</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                {% if item.table_id == id %}
                <tr>
                    <td>{{ item.description }}</td>
                    <td>{{ item.quantity }}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>

<div class="row my-4">
    
</div>

{% endblock %}

templates/Invoice/item_delete.html
{% extends 'partials/base.html' %}
{% block title %}Item Delete Page{% endblock %}

{% block content %}
<div class="row my-4">
    <div class="col-md-6 offset-md-3">
        <div class="border p-3 bg-white">
            <h3>Delete Item</h3>
            <hr>
            <form method="POST">
                <div class="alert alert-danger">
                    <h4>Are you sure, you want to delete?</h4>
                </div>
                {% csrf_token %}
                <a class="btn btn-secondary btn-sm" href="{% url 'add-items' id %}">Cancel</a>
                <input class="btn btn-danger btn-sm" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/Invoice/item_update.html
{% extends 'partials/base.html' %}
{% block title %}Item update Page{% endblock %}

{% block content %}

<div class="row my-4">
    <div class="col-md-6 offset-md-3">
        <div class="border p-3 bg-white">
            <h3>Edit Item</h3>
            <hr>
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <a class="btn btn-secondary btn-sm" href="{% url 'add-items' id %}">Cancel</a>
                <input class="btn btn-info btn-sm" type="submit" value="Update">
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/Invoice/letter_info.html
{% extends 'partials/base.html' %}


{% block styling %}
    #id_source{
        width:350px;
    }
    #id_destination{
        width:350px;
    }
{% endblock %}


{% block content %}
<div class="card" style="margin:20px;">
    <div class="card-body">
<form method="POST">
    {% csrf_token %}
    
    <div class="form-group">
        <div style="font-weight: bold;">
            <p>To,</p>
            <p>The Security In-charge</p>
            <p>{{form.address}}</p>
        </div>
        <div style="font-weight: bold; text-decoration: underline; margin:30px;">
            <p style="margin-left:30px;"> Sub: Request for {{form.returnable}} Gate Pass</p>
        </div>
        <div>
            <p>This is to request you to allow the following from {{form.source}}</p>
            <p>to {{form.destination}}</p>
        </div>
        <div>
            <p>Signature of {{form.name}}</p>
        </div>
    </div>
    <input style="margin-top:40px;" class="btn btn-info" type="submit" value="Proceed to add items">
</form>
</div>
</div>
<!-- 
<div>
    <button class="btn btn-info " style="margin:20px;" type="button">Button</button>
    <button class="btn btn-info " type="button">Button</button>
</div> -->
{% endblock %}

templates/Invoice/letter_items.html
{% extends 'partials/base.html' %}


{% block styling %}
    #id_source{
        width:350px;
    }
    #id_destination{
        width:350px;
    }
{% endblock %}


{% block content %}

<div class="row my-4">
    <div class="col-md-5" style="margin-left:20px;" >
        <div class="bg-info text-white p-3 mb-3 ">
            <h5>Letter information</h5>
            <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form_info }}
                    <input class="btn btn-success btn-block" type="submit" value="Save">
                </form>
        </div>
    
    </div>
</div>

<div class="row my-4">
    <div class="col-md-3" style="margin-left:20px;">
        {% for message in messages %}
        {% if message %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
        {% endif %}
        {% endfor %} 
        <div class="bg-info text-white p-3 mb-3 ">
            <h5>Add New Items</h5>
            <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input class="btn btn-success btn-block" type="submit" value="Add">
                </form>
        </div>
        <a href="{% url 'generate-pdf' id 'attachment' %}" class=" active alert alert-info" > Generate PDF </a>
        <a href="{% url 'generate-pdf' id 'inline' %}" style="margin-left:20px;" target="_blank" class=" active alert alert-info" > Preview PDF </a>
    </div>
    <div class="col-md-7" style="margin-right:10px;">
        <table class="table bg-white">
            <thead class="bg-info text-white">
                <tr>
                    <th scope="col">Description</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Activity</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                {% if item.table_id == id %}
                <tr>
                    <td>{{ item.description }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <a class="btn btn-info btn-sm mr-2"
                            href="{% url 'update-items' id item.id %}">Edit</a>
                        <a class="btn btn-danger btn-sm ml-2"
                            href="{% url 'delete-items' id item.id %}">Delete</a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>
{% endblock %}